from typing import NamedTuple, Any
from datetime import datetime
from enum import Enum


class QueueEvent(Enum):
    HEARTRATE_SENSOR_EVENT = 'BioHR'
    ECG_SENSOR_EVENT = 'BioECG'
    TEMPERATURE_SENSOR_EVENT = 'BioTEMP'
    BATTERY_SENSOR_EVENT = 'BioBAT'
    RR_SENSOR_EVENT = 'BioRR'
    RR1_SENSOR_EVENT = 'BioRR1'
    RR2_SENSOR_EVENT = 'BioRR2'
    IMU_SENSOR_EVENT = 'BioIMU'

    PR_SENSOR_EVENT = 'OxiPR'
    SPO2_SENSOR_EVENT = 'OxiSPO2'

    MQTT_SYNC_REQ_EVENT = 'MQTT_SYNC_REQ_EVENT'  
    MQTT_SYNC_REP_EVENT = 'MQTT_SYNC_REP_EVENT' 
    MQTT_SYNC_FINAL_REP_EVENT = 'MQTT_SYNC_FINAL_REP_EVENT' 
    MQTT_STATUS_REQ_EVENT = 'MQTT_STATUS_REQ_EVENT'
    MQTT_STATUS_REP_EVENT = 'MQTT_STATUS_REP_EVENT'   
    MQTT_WILL_EVENT = 'MQTT_WILL_EVENT' 
    MQTT_PAIR_REQ_EVENT = 'MQTT_PAIR_REQ_EVENT' 
    MQTT_PAIR_REP_EVENT = 'MQTT_PAIR_REP_EVENT' 


class QueueItem(NamedTuple):
    id: QueueEvent
    timestamp: datetime
    data: Any
